config {
    type: "table",
    schema: "silver"
}

SELECT
    oi.order_item_id,
    oi.order_id,
    oi.user_id,
    oi.product_id,
    ROUND(oi.sale_price, 2) AS sale_price,
    oi.status,
    o.created_at AS order_created_at,
    o.num_of_item
FROM ${ref("stg_order_items")} oi
    LEFT JOIN ${ref("stg_orders")} o ON oi.ORDER_ID = o.ORDER_ID
WHERE oi.sale_price > 0
    AND o.status != 'Cancelled'